FROM docker.io/library/golang:1.21.7 AS builder

ENV APP_NAME=streaming

COPY src/main.go /home/go/src/
WORKDIR /home/go/src
RUN go mod init ${APP_NAME}
RUN go mod tidy
#RUN GOOS=linux GOARCH=amd64 go build -o ${APP_NAME}_linux-amd64
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ${APP_NAME}_linux-arm64
RUN GOOS=linux GOARCH=arm64 go build -o ${APP_NAME}_linux-arm64

FROM docker.io/library/debian:bookworm-slim
ENV APP_NAME=streaming
RUN useradd -m -d /home/noadm -s /bin/bash noadm
COPY --from=builder /home/go/src/${APP_NAME}_linux-arm64 /home/noadm

WORKDIR /home/noadm

USER noadm

CMD ["/bin/bash"]
